version: "3.9"

services:
  backend:
    build: ./backend/codemaestro
    restart: always
    ports:
      - "${SPRING_BOOT_PORT:-9090}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    profiles:
      - backend
      - prod

  frontend:
    build:
      context: ./frontend/codemaestro
    restart: always
    ports:
      - "3000:3000"
    profiles:
      - frontend
      - prod
